/**
 * Central registry of all animations in the playground.
 * Each entry describes one animation and where to find its files.
 */
export const animations = [
  {
    id: '001-folder-books',
    name: 'Folder Books',
    description: 'A yellow frosted folder with overlapping book covers that pop out on hover.',
    type: 'gsap',
    tags: ['folder', 'hover', 'books', 'glassmorphism', '3d'],
    folder: '/animations/001-folder-books',
  },
  {
    id: '002-details-edit',
    name: 'Details Edit Split',
    description: 'A details card that splits into jelly-bouncy editable fields on edit, then merges back on save or cancel.',
    type: 'gsap',
    tags: ['form', 'edit', 'jelly', 'micro-interaction', 'card'],
    folder: '/animations/002-details-edit',
  },
  {
    id: '003-login-user',
    name: 'Fluid Login',
    description: 'A matte-black user icon with a prismatic fluid ring. Tap to spin the glow, fill the icon, then reveal a success check.',
    type: 'gsap',
    tags: ['login', 'fluid', 'glow', 'micro-interaction', 'success'],
    folder: '/animations/003-login-user',
  },
  {
    id: '004-country-swipe',
    name: 'Country Swipe',
    description: 'Swipe a 9:16 country card out of a soft-shadow frame — it rotates 90° on its vertical axis as the next European destination spins in.',
    type: 'gsap',
    tags: ['swipe', 'card', '3d', 'rotate', 'countries', 'drag'],
    folder: '/animations/004-country-swipe',
  },
  {
    id: '005-guardian-angel',
    name: 'The Guardian Angel',
    description: 'A halftone angel poster card with 3D hover tilt — the side under your cursor dips away, wings flap slowly, and the backlight glow drifts left to right.',
    type: 'gsap',
    tags: ['3d', 'tilt', 'hover', 'card', 'poster', 'glow'],
    folder: '/animations/005-guardian-angel',
  },
  {
    id: '006-tiger-cat',
    name: 'Tiger Cat',
    description: 'An orange tiger-striped cat matching a flat illustration — the white sparkles inside its pupils follow your cursor.',
    type: 'css-js',
    tags: ['cat', 'eyes', 'cursor', 'tiger', 'illustration'],
    folder: '/animations/006-tiger-cat',
  },
  {
    id: '007-star-rating',
    name: 'Star Rating',
    description: 'Hover a rating to highlight it, then click — stars fly up from the option and fill the row above with a left-to-right stagger. Click anywhere to reset.',
    type: 'gsap',
    tags: ['stars', 'rating', 'hover', 'micro-interaction', 'fly'],
    folder: '/animations/007-star-rating',
  },
  {
    id: '008-india-stack',
    name: 'India Stack',
    description: 'Drag a Polaroid travel card left or right — it flips 180° on its Y axis and settles to the back of the stack, revealing the next destination.',
    type: 'gsap',
    tags: ['swipe', 'drag', '3d', 'cards', 'stack', 'india', 'flip'],
    folder: '/animations/008-india-stack',
  },
  {
    id: '009-expand-buttons',
    name: 'Expand Buttons',
    description: 'Icon pills that expand right with a soft bounce to reveal their labels — rotating inner sheen on hover, same bounce on leave, one open at a time.',
    type: 'gsap',
    tags: ['buttons', 'hover', 'expand', 'bounce', 'micro-interaction'],
    folder: '/animations/009-expand-buttons',
  },
  {
    id: '010-gallery-folder',
    name: 'Gallery Folder',
    description: 'Scroll the photo grid, then pull past the top or pinch — it bounces into a frosted blue folder. Tap to open again.',
    type: 'gsap',
    tags: ['gallery', 'folder', 'pinch', 'drag', 'photos', 'glassmorphism'],
    folder: '/animations/010-gallery-folder',
  },
  {
    id: '011-sketchbook',
    name: 'Sketchbook',
    description: 'Open a geometric sketchbook, drag page corners to turn, pick a color, and draw freehand — clear any page when you want a fresh sheet.',
    type: 'gsap',
    tags: ['book', 'draw', 'drag', 'pages', 'sketch', 'color', 'interactive'],
    folder: '/animations/011-sketchbook',
  },
  {
    id: '012-movie-dropdown',
    name: 'Movie Dropdown',
    description: 'Chamfered movie picker — open with a bounce, then swap titles letter-by-letter with a cascading blur when you pick a new film.',
    type: 'gsap',
    tags: ['dropdown', 'text', 'blur', 'cascade', 'bounce', 'micro-interaction'],
    folder: '/animations/012-movie-dropdown',
  },
];
